import 'package:flame_audio/flame_audio.dart';

import 'storage.dart';

/// All sound files are tiny synthesized WAVs generated by
/// `tools/generate_audio.py` into `assets/audio/`.
class AudioManager {
  AudioManager._();

  static final instance = AudioManager._();

  static const _sfx = [
    'coin.wav',
    'jump.wav',
    'roll.wav',
    'swipe.wav',
    'crash.wav',
    'stumble.wav',
    'powerup.wav',
    'click.wav',
    'gameover.wav',
    'highscore.wav',
  ];

  bool _loaded = false;
  bool _musicPlaying = false;
  bool _musicPaused = false;

  bool get soundOn => Storage.instance.soundOn;
  bool get musicOn => Storage.instance.musicOn;

  Future<void> init() async {
    if (_loaded) return;
    try {
      await FlameAudio.audioCache.loadAll([..._sfx, 'music.wav']);
      _loaded = true;
    } catch (_) {
      // Audio is never allowed to take the game down (e.g. web autoplay
      // restrictions or a missing device backend on desktop Linux).
    }
  }

  void play(String name, {double volume = 1.0}) {
    if (!soundOn) return;
    try {
      FlameAudio.play(name, volume: volume);
    } catch (_) {}
  }

  void coin() => play('coin.wav', volume: 0.5);
  void jump() => play('jump.wav', volume: 0.6);
  void roll() => play('roll.wav', volume: 0.6);
  void swipe() => play('swipe.wav', volume: 0.4);
  void crash() => play('crash.wav', volume: 0.9);
  void stumble() => play('stumble.wav', volume: 0.8);
  void powerup() => play('powerup.wav', volume: 0.7);
  void click() => play('click.wav', volume: 0.5);
  void gameover() => play('gameover.wav', volume: 0.8);
  void highscore() => play('highscore.wav', volume: 0.9);

  Future<void> startMusic() async {
    if (!musicOn || _musicPlaying) return;
    try {
      await FlameAudio.bgm.play('music.wav', volume: 0.45);
      _musicPlaying = true;
      _musicPaused = false;
    } catch (_) {}
  }

  Future<void> stopMusic() async {
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {}
    _musicPlaying = false;
    _musicPaused = false;
  }

  Future<void> pauseMusic() async {
    if (!_musicPlaying || _musicPaused) return;
    try {
      await FlameAudio.bgm.pause();
    } catch (_) {}
    _musicPaused = true;
  }

  Future<void> resumeMusic() async {
    if (!_musicPlaying || !_musicPaused) return;
    try {
      await FlameAudio.bgm.resume();
    } catch (_) {}
    _musicPaused = false;
  }

  /// Music plays during runs only, so switching it on just persists the
  /// preference for the next run; switching it off silences immediately.
  Future<void> setMusicOn(bool on) async {
    Storage.instance.musicOn = on;
    if (!on) await stopMusic();
  }
}
