import 'package:flame_audio/flame_audio.dart';

import 'storage.dart';

/// All sound files are tiny synthesized WAVs generated by
/// `tools/generate_audio.py` into `assets/audio/`.
class AudioManager {
  AudioManager._();

  static final instance = AudioManager._();

  static const _sfx = [
    'coin.wav',
    'coin_1.wav',
    'coin_2.wav',
    'coin_3.wav',
    'coin_4.wav',
    'jump.wav',
    'land.wav',
    'roll.wav',
    'swipe.wav',
    'whoosh.wav',
    'crash.wav',
    'crash_wood.wav',
    'crash_clang.wav',
    'stumble.wav',
    'powerup.wav',
    'click.wav',
    'beep.wav',
    'go.wav',
    'gameover.wav',
    'highscore.wav',
  ];

  bool _loaded = false;
  bool _musicPlaying = false;
  bool _musicPaused = false;

  /// Pre-warmed low-latency players, one pool per effect. Creating a native
  /// player per play (what FlameAudio.play does) backs up on Android under
  /// rapid fire — sounds then drain seconds late.
  final Map<String, AudioPool> _pools = {};

  bool get soundOn => Storage.instance.soundOn;
  bool get musicOn => Storage.instance.musicOn;

  Future<void> init() async {
    if (_loaded) return;
    try {
      await FlameAudio.audioCache.loadAll([..._sfx, 'music.wav']);
      for (final f in _sfx) {
        _pools[f] = await FlameAudio.createPool(f,
            minPlayers: 1, maxPlayers: f.startsWith('coin') ? 3 : 2);
      }
      _loaded = true;
    } catch (_) {
      // Audio is never allowed to take the game down (e.g. web autoplay
      // restrictions or a missing device backend on desktop Linux).
    }
  }

  void play(String name, {double volume = 1.0}) {
    if (!soundOn) return;
    try {
      final pool = _pools[name];
      if (pool != null) {
        pool.start(volume: volume);
      } else {
        FlameAudio.play(name, volume: volume);
      }
    } catch (_) {}
  }

  /// Coin ding that climbs a pentatonic ladder while a pickup chain is
  /// alive — `combo` 0 plays the base note, 4+ the top one.
  void coin(int combo) {
    final step = combo.clamp(0, 4);
    play(step == 0 ? 'coin.wav' : 'coin_$step.wav', volume: 0.5);
  }

  void jump() => play('jump.wav', volume: 0.6);
  void land() => play('land.wav', volume: 0.45);
  void roll() => play('roll.wav', volume: 0.6);
  void swipe() => play('swipe.wav', volume: 0.4);
  void whoosh() => play('whoosh.wav', volume: 0.7);
  void crashTrain() => play('crash.wav', volume: 0.9);
  void crashWood() => play('crash_wood.wav', volume: 0.9);
  void crashClang() => play('crash_clang.wav', volume: 0.9);
  void stumble() => play('stumble.wav', volume: 0.8);
  void powerup() => play('powerup.wav', volume: 0.7);
  void click() => play('click.wav', volume: 0.5);
  void beep() => play('beep.wav', volume: 0.5);
  void go() => play('go.wav', volume: 0.6);
  void gameover() => play('gameover.wav', volume: 0.8);
  void highscore() => play('highscore.wav', volume: 0.9);

  Future<void> startMusic() async {
    if (!musicOn || _musicPlaying) return;
    try {
      await FlameAudio.bgm.play('music.wav', volume: 0.45);
      _musicPlaying = true;
      _musicPaused = false;
    } catch (_) {}
  }

  Future<void> stopMusic() async {
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {}
    _musicPlaying = false;
    _musicPaused = false;
  }

  Future<void> pauseMusic() async {
    if (!_musicPlaying || _musicPaused) return;
    try {
      await FlameAudio.bgm.pause();
    } catch (_) {}
    _musicPaused = true;
  }

  Future<void> resumeMusic() async {
    if (!_musicPlaying || !_musicPaused) return;
    try {
      await FlameAudio.bgm.resume();
    } catch (_) {}
    _musicPaused = false;
  }

  /// Music plays during runs only, so switching it on just persists the
  /// preference for the next run; switching it off silences immediately.
  Future<void> setMusicOn(bool on) async {
    Storage.instance.musicOn = on;
    if (!on) await stopMusic();
  }
}
